### ISSUE TITLE
Typescript definition file

### ISSUE THREAD

**Issue by MatteoGabriele** [MatteoGabriele/vue-gtag-next#4]
create new definition file

**Comment by MatteoGabriele** [comment]
hi @namoscato 
since you did a great job with the previous version of the library definition file, do you happen to have some time to handle this task? would be great cause I just finished the new version for Vue 3 and it's a bit different + i still need to finish the Documentation and will take me a while.

**Comment by namoscato** [comment]
@MatteoGabriele, yeah I can help out – probably sometime over the next two weeks? Is there any documentation I can go off in the meantime?

**Comment by MatteoGabriele** [comment]
That's perfect. I'm actually about to write the documentation so maybe once u have time I'll be done with it. This is the only "documentation" I have written https://github.com/MatteoGabriele/vue-gtag/issues/168#issuecomment-692298933 just a few words really.

I'll keep u updated

Thanks again
