### ISSUE TITLE
How to use in nuxtjs?

### ISSUE THREAD

**Issue by standfv** [MatteoGabriele/vue-gtag-next#7]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

What are you reporting?

### Expected behavior

Tell us what you think should happen.

### Actual behavior

Tell us what actually happens.

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-gtag`: 

Then, specify:

1. Operating system:
2. Browser and version:

### Reproducible Demo

Please take the time to create a new app that reproduces the issue or at least some code example

Demonstrable issues gets fixed faster.

**Comment by MatteoGabriele** [comment]
This ticket left uncompleted makes me sad. If you have just a question just type it, ok?
Did u try it? What's not working? etc..
